spring:
  datasource:
    url: jdbc:h2:mem:testdb

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
  messages:
    basename: i18n.messages
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    consumer:
      group-id: "salebooks"

jwt:
  private.key: classpath:jwtRS256.key
  public.key: classpath:jwtRS256.key.pub
library:
  kafka-topic-name: ${KAFKA_TOPIC:book-sales}