testing:
  filename: /question.csv
  filename_ru_RU: /question_ru_RU.csv
  count: 3

spring:
  messages:
    basename: i18n.messages

logging:
  file:
    name: log-file.log

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true